export {
  assertFsEvent,
  isFsDirCreatePayload,
  isFsDirRemovePayload,
  isFsEvent,
  isFsFileContentEvent,
  isFsFileContentPayload,
  isFsBranchForkEvent,
  isFsBranchForkPayload,
  isFsBranchMergeEvent,
  isFsBranchMergePayload,
  isFsFastForwardMergeEvent,
  isFsThreeWayMergeEvent,
  isFsMergeChange,
  isFsMergeChangeEvent,
  isFsMergeChangePayload,
  isFsMergeConflictEvent,
  isFsMergeConflictPayload,
  isFsMergeResolveEvent,
  isFsMergeResolvePayload,
  isFsFileCreatePayload,
  isFsFileDeletePayload,
  isFsFilePatchPayload,
  isFsFileWritePayload,
  isFsRenamePayload,
  isValidFsPath,
  FsEventValidationError,
  type FsEvent,
  type FsDirCreateEvent,
  type FsDirCreatePayload,
  type FsDirRemoveEvent,
  type FsDirRemovePayload,
  type FsFileContentEvent,
  type FsFileContentPayload,
  type FsBranchForkEvent,
  type FsBranchForkPayload,
  type FsBranchMergeEvent,
  type FsBranchMergePayload,
  type FsBranchFastForwardMergePayload,
  type FsBranchThreeWayMergePayload,
  type FsMergeChange,
  type FsMergeChangeEvent,
  type FsMergeChangePayload,
  type FsMergeConflictEvent,
  type FsMergeConflictKind,
  type FsMergeConflictPayload,
  type FsMergeConflictReason,
  type FsMergeNodeRef,
  type FsMergeResolveEvent,
  type FsMergeResolvePayload,
  type FsMergeRevisionRef,
  type FsMergeSideRef,
  type FsFileCreateEvent,
  type FsFileCreatePayload,
  type FsFileDeleteEvent,
  type FsFileDeletePayload,
  type FsFilePatchEvent,
  type FsFilePatchPayload,
  type FsFileWriteEvent,
  type FsFileWritePayload,
  type FsRenameEvent,
  type FsRenamePayload,
} from "./events.js";
export { fsInitialState, fsReducer, FsReducerError } from "./reducer.js";
export {
  WORKTREE_DIGEST_VERSION,
  WorktreeDigestError,
  worktreeDigest,
  worktreeProjection,
  type WorktreeDigestErrorCode,
  type WorktreeFileState,
  type WorktreeProjection,
} from "./worktree.js";
export {
  BRANCH_EVENT_VERSION,
  BRANCH_NAME_PATTERN,
  createBranch,
  branchMetadataStreamId,
  branchContentStreamPrefix,
  isBranchContentStreamId,
  isBranchName,
  resolveBranch,
  type BranchInfo,
  type CreateBranchOptions,
  type CreateBranchResult,
} from "./branch.js";
export {
  BranchResolutionError,
  resolveBranchLog,
  type BranchDump,
  type Dump,
  type MergeDump,
} from "./resolve.js";
export { diffText } from "./patch/diff.js";
export { mergeTextBytes, type TextMergeResult } from "./patch/merge.js";
export {
  conflictIdentity,
  mergePlanId,
  sameRevision,
  type FsMergeConflictIdentity,
  type FsMergePlanIdentity,
} from "./merge-integrity.js";
export {
  chooseWriteEvent,
  type FsPatchAction,
  type FsWriteAction,
  type FsWriteChoice,
} from "./patch/choose.js";
export {
  applyPatch,
  digestBytes,
  isPatchOps,
  patchResultSize,
  PatchError,
  type PatchErrorCode,
  type PatchOp,
  type PatchOps,
} from "./patch/ops.js";
export {
  ContentIntegrityError,
  DirectoryExistsError,
  DirectoryNotEmptyError,
  DirectoryNotFoundError,
  FileExistsError,
  FileNotFoundError,
  FsHttpError,
  InvalidFsPathError,
  InvalidRenameError,
  RepoExistsError,
  RepoNotFoundError,
  StreamFs,
  StreamFsError,
  StreamFsRepo,
  type FsDispatchReceipt,
  type StreamFsOptions,
} from "./fs.js";
export { FS_EVENT_VERSION } from "./version.js";
export {
  applyThreeWayMerge,
  mergeFastForward,
  mergeThreeWay,
  planThreeWayMerge,
  resolveMergeConflict,
  ThreeWayMergeError,
  type FastForwardMergeReceipt,
  type MergeResolutionReceipt,
  type ThreeWayMergeContentDependency,
  type ThreeWayMergePlan,
  type ThreeWayMergeReceipt,
} from "./merge.js";
export { BASE_NONE } from "./fencing.js";
export {
  emptyFsWatchState,
  fsEventsToWatchEvents,
  StreamFsWatcherImpl,
  watch,
  WATCH_EVENT_NAMES,
  type FsWatchState,
  type StreamFsRepoWatchOptions,
  type StreamFsWatcher,
  type WatchEventName,
  type WatchEventRecord,
  type WatchMappingResult,
  type WatchOptions,
} from "./watch.js";
export {
  bootstrapRead,
  compactSnapshot,
  createSnapshot,
  reduceSnapshotPlusTail,
  SnapshotIntegrityError,
  type BootstrapReadResult,
  type SnapshotReceipt,
  type SnapshotRoot,
} from "./snapshot.js";
export {
  assertCompleteMergeStage,
  contentMap,
  emptyTree,
  listTree,
  sortedTree,
  treeDigest,
  unresolvedMergeConflicts,
  withContentMap,
  type FsDirState,
  type FsFileState,
  type FsTombstoneState,
  type FsTree,
} from "./tree.js";
