import { randomBytes } from "node:crypto";
import { isDurableConflict, isDurableNotFound } from "@eforest/client";
import {
  canonicalJson,
  isEvent,
  sha256Hex,
  OFFSET_BEFORE_FIRST,
  type Event,
  type Offset,
} from "@eforest/protocol";
import { offsetForOrdinal, isWellFormedOffset } from "@eforest/protocol/offset-allocation";
import {
  admitLease,
  capabilityBaseDigest,
  capabilityForLease,
  capabilityTokenDigest,
  capabilityTokenForFence,
  authorizeCapability,
  leaseAcquiredEvent,
  leaseHeartbeatEvent,
  leaseInitialStateForStream,
  leaseReleasedEvent,
  leaseRevokedEvent,
  leaseStreamId,
  replayLeaseLog,
  type AgentCapability,
  type CapabilityTarget,
  type LeaseRecord,
  type LeaseState,
} from "@eforest/loop";
import {
  isRunAppendEvent,
  isRunEvent,
  runExitedEvent,
  runHeartbeatEvent,
  runInitialStateForStream,
  runMutationIntentEvent,
  runMutationAcceptedEvent,
  runRevokedEvent,
  runStreamId,
  replayRunLog,
  type RunEvent,
  type RunAppendEvent,
  type RunState,
  type RunRevocationReason,
} from "@eforest/loop";
import type {
  AgentAdapter,
  AgentAdapterContext,
  AgentAdapterResult,
  AgentMutationReceipt,
  AgentMutationRequest,
} from "@eforest/loop";
import { ScriptedCrashError } from "@eforest/loop";
import type { WorkspaceManifest } from "@eforest/loop";
import { checkQueueProof, type QueueProof, type QueueSourceStream } from "@eforest/tasks";
import type { TaskBranchRef, TaskRole } from "@eforest/tasks";
import { projectStreamId, replayProjectLog } from "./loop/index.js";
import type { StreamAdapter } from "./official.js";

const SAFE_ID = /^[A-Za-z0-9._~-]{1,160}$/;
const SAFE_NAME = /^[a-z0-9](?:-?[a-z0-9])*$/;
const OFFSET = /^-1$|^[0-9]{16}_[0-9]{16}$/;
const SECRET = /Bearer\s+[A-Za-z0-9._~-]+|(?:ef_cli_|cap_v1\.|sk-|gh[pousr]_)[A-Za-z0-9._~-]+/i;

export interface AgentRunAcquireInput {
  readonly org: string;
  readonly repo: string;
  readonly taskId: string;
  readonly runId: string;
  readonly actor: string;
  readonly role: TaskRole;
  readonly branch: TaskBranchRef;
  readonly projectOffset: Offset | "-1";
  readonly queueProof: QueueProof;
}

export interface AgentRunLeaseInput {
  readonly org: string;
  readonly repo: string;
  readonly taskId: string;
  readonly leaseId: string;
  readonly actor: string;
  readonly token: string;
}

export interface AgentRunEventInput {
  readonly org: string;
  readonly repo: string;
  readonly taskId: string;
  readonly runId: string;
  readonly actor: string;
  readonly token: string;
  readonly expectedOffset: Offset | "-1";
  readonly event: RunAppendEvent;
}

export interface AgentRunMutationInput extends Omit<AgentRunEventInput, "event"> {
  /** Deprecated compatibility field; mutation intents are generated by the coordinator. */
  readonly event?: RunAppendEvent;
  readonly operationId: string;
  readonly target: "branch" | "evidence" | "verdict";
  readonly stream: string;
  readonly expectedTargetOffset: Offset | "-1";
  readonly mutation: Event;
}

export interface AgentRunAcquireResult {
  readonly lease: LeaseRecord;
  readonly capability: AgentCapability;
  readonly token: string;
  readonly run: RunState;
  readonly leaseOffset: Offset;
  readonly runOffset: Offset;
}

export interface AgentRunLeaseResult {
  readonly lease: LeaseRecord | null;
  readonly capability?: AgentCapability;
  readonly token?: string;
  readonly run?: RunState;
  readonly offset?: Offset;
}

export interface AgentRunMutationResult {
  readonly receipt: AgentMutationReceipt;
  readonly run: RunState;
  readonly runOffset: Offset;
}

export class AgentRunError extends Error {
  constructor(readonly code: string) {
    super(code);
    this.name = "AgentRunError";
  }
}

function offsetOf(record: unknown, index: number): Offset {
  const candidate =
    record !== null && typeof record === "object" && !Array.isArray(record)
      ? (record as Record<string, unknown>).offset
      : undefined;
  return typeof candidate === "string" &&
    candidate !== OFFSET_BEFORE_FIRST &&
    isWellFormedOffset(candidate)
    ? candidate
    : offsetForOrdinal(index);
}

function normalizeRecord(record: unknown, index: number): Event & { readonly offset: Offset } {
  if (record === null || typeof record !== "object" || Array.isArray(record)) {
    throw new AgentRunError("run/malformed-record");
  }
  const value = record as Record<string, unknown>;
  const event = { type: value.type, payload: value.payload, ts: value.ts };
  if (!isEvent(event)) throw new AgentRunError("run/malformed-record");
  return { ...event, offset: offsetOf(record, index) };
}

function headOf(records: readonly (Event & { readonly offset?: Offset })[]): Offset | "-1" {
  return records.length === 0 ? OFFSET_BEFORE_FIRST : offsetOf(records.at(-1), records.length - 1);
}

function validOffset(value: unknown): value is Offset | "-1" {
  return (
    typeof value === "string" && OFFSET.test(value) && (value === "-1" || isWellFormedOffset(value))
  );
}

function validAcquire(input: AgentRunAcquireInput): void {
  if (
    !SAFE_NAME.test(input.org) ||
    !SAFE_NAME.test(input.repo) ||
    !SAFE_ID.test(input.taskId) ||
    !SAFE_ID.test(input.runId)
  ) {
    throw new AgentRunError("lease/invalid-target");
  }
  if (input.actor.length === 0 || input.actor.length > 256 || /\s/.test(input.actor)) {
    throw new AgentRunError("lease/invalid-target");
  }
  if (input.role !== "builder" && input.role !== "critic")
    throw new AgentRunError("lease/invalid-target");
  if (
    !validOffset(input.projectOffset) ||
    input.branch.stream.length === 0 ||
    input.branch.head === "-1"
  ) {
    throw new AgentRunError("lease/invalid-target");
  }
  if (input.queueProof.queue.stream !== `repo-issues:${input.org}/${input.repo}`) {
    throw new AgentRunError("lease/invalid-target");
  }
}

function safeEvent(value: unknown): value is Event {
  if (!isEvent(value)) return false;
  try {
    return !SECRET.test(canonicalJson(value));
  } catch {
    return false;
  }
}

function leaseTarget(lease: LeaseRecord, target: AgentRunMutationInput): CapabilityTarget {
  return { kind: target.target, stream: target.stream };
}

export interface AgentRunCoordinatorOptions {
  readonly streams: StreamAdapter;
  readonly now?: () => number;
  readonly random?: (size: number) => Uint8Array;
}

/**
 * Durable E6-T07 coordinator. The stream is the source of truth: the in-memory
 * mutex only reduces local contention; every decision is replayed and every append
 * carries the observed application offset as the official-store fence.
 */
export class AgentRunCoordinator {
  private readonly streams: StreamAdapter;
  private readonly now: () => number;
  private readonly random: (size: number) => Uint8Array;
  private readonly locks = new Map<string, Promise<void>>();

  constructor(options: AgentRunCoordinatorOptions) {
    this.streams = options.streams;
    this.now = options.now ?? Date.now;
    this.random = options.random ?? ((size) => randomBytes(size));
  }

  async acquire(
    input: Omit<AgentRunAcquireInput, "actor"> & { readonly actor: string },
  ): Promise<AgentRunAcquireResult> {
    validAcquire(input);
    const leaseStream = leaseStreamId(input.org, input.repo, input.taskId);
    const runStream = runStreamId(input.org, input.runId);
    return this.withLock(leaseStream, async () => {
      const [currentProof, project, currentLease] = await Promise.all([
        this.currentQueueProof(input.queueProof),
        this.currentProject(input.org, input.repo),
        this.readLease(leaseStream),
      ]);
      const leaseId = this.identifier("lease");
      const capabilityId = this.identifier("cap");
      const tokenBase = Buffer.from(this.random(32)).toString("base64url");
      const token = capabilityTokenForFence(tokenBase, currentLease.nextFence);
      const admission = admitLease({
        taskId: input.taskId,
        actor: input.actor,
        role: input.role,
        runId: input.runId,
        leaseId,
        branch: input.branch,
        evidenceStream: `evidence:${input.org}/${input.repo}/issue/${input.taskId}`,
        proof: input.queueProof,
        currentProof,
        projectStatus: project.status,
        projectOffset: input.projectOffset,
        currentProjectOffset: project.head,
        currentLease,
        queueProofDigest: currentProof.digest,
        capabilityId,
        capabilityBaseDigest: capabilityBaseDigest(token),
        capabilityTokenDigest: capabilityTokenDigest(token),
        createdAt: this.now(),
      });
      if (!admission.ok) throw new AgentRunError(admission.reason);
      await this.ensureStream(leaseStream);
      const leaseOffset = await this.appendFenced(
        leaseStream,
        leaseAcquiredEvent(admission.lease, this.now()),
        currentLease.head,
        leaseId,
      );
      try {
        await this.ensureStream(runStream);
        const existingRun = await this.readRun(runStream);
        if (existingRun.status !== "created" || existingRun.runId !== "") {
          throw new AgentRunError("run/already-exists");
        }
        const started: RunEvent = {
          type: "run.started",
          payload: {
            v: 1,
            run: runStream,
            taskId: input.taskId,
            actor: input.actor,
            role: input.role,
            leaseId,
            capabilityId,
            branch: input.branch,
            evidenceStream: `evidence:${input.org}/${input.repo}/issue/${input.taskId}`,
            queueProofDigest: currentProof.digest,
            projectOffset: project.head,
          },
          ts: this.now(),
        };
        const runOffset = await this.appendFenced(runStream, started, OFFSET_BEFORE_FIRST, leaseId);
        const lease = admission.lease;
        return {
          lease,
          capability: capabilityForLease(lease, token),
          token,
          run: replayRunLog(runStream, [started]),
          leaseOffset,
          runOffset,
        };
      } catch (error) {
        // A lease without its run-start record cannot be held indefinitely. The
        // revocation is best-effort but remains fenced to the accepted lease record.
        try {
          const state = await this.readLease(leaseStream);
          if (state.active?.leaseId === admission.lease.leaseId) {
            await this.appendFenced(
              leaseStream,
              leaseRevokedEvent(
                admission.lease.leaseId,
                state.active.fence,
                "run-start-failed",
                this.now(),
              ),
              state.head,
              `${leaseId}-rollback`,
            );
          }
        } catch {
          // Preserve the original failure; replay exposes an active lease for repair.
        }
        throw error;
      }
    });
  }

  async heartbeat(input: AgentRunLeaseInput): Promise<AgentRunLeaseResult> {
    return this.withLeaseLock(input, async (leaseStream, state) => {
      const active = this.requireActor(state, input);
      await this.assertProjectLive(leaseStream, state, active);
      const parsed = this.parseCurrentOrRecoverableToken(active, input.token);
      if (parsed.kind === "invalid") throw new AgentRunError("capability/invalid-token");
      if (parsed.kind === "recover") {
        return this.leaseResult(active, parsed.token);
      }
      const nextFence = active.fence + 1;
      const nextToken = capabilityTokenForFence(input.token, nextFence);
      const leaseOffset = await this.appendFenced(
        leaseStream,
        leaseHeartbeatEvent(
          active.leaseId,
          nextFence,
          capabilityTokenDigest(nextToken),
          this.now(),
        ),
        state.head,
        `${active.leaseId}-heartbeat-${String(nextFence)}`,
      );
      const current = await this.readLease(leaseStream);
      const nextLease = current.active;
      if (nextLease === null) throw new AgentRunError("lease/not-active");
      const runStream = runStreamId(nextLease.org, nextLease.runId);
      const run = await this.readRun(runStream);
      if (run.status === "running") {
        await this.appendFenced(
          runStream,
          runHeartbeatEvent(nextFence, this.now()),
          run.head,
          `${nextLease.leaseId}-run-heartbeat-${String(nextFence)}`,
        );
      }
      return {
        ...this.leaseResult(nextLease, nextToken),
        run: await this.readRun(runStream),
        offset: leaseOffset,
      };
    });
  }

  async release(input: AgentRunLeaseInput): Promise<AgentRunLeaseResult> {
    return this.finishLease(input, "released");
  }

  async revoke(
    input: AgentRunLeaseInput & { readonly reason: string },
  ): Promise<AgentRunLeaseResult> {
    if (!/^[a-z0-9-]{1,64}$/.test(input.reason)) throw new AgentRunError("lease/invalid-target");
    return this.finishLease(input, "revoked", input.reason);
  }

  async appendRunEvent(
    input: AgentRunEventInput,
  ): Promise<{ readonly offset: Offset; readonly run: RunState }> {
    if (!validOffset(input.expectedOffset) || !isRunAppendEvent(input.event)) {
      throw new AgentRunError("run/invalid-event");
    }
    const leaseStream = leaseStreamId(input.org, input.repo, input.taskId);
    return this.withLock(leaseStream, async () => {
      const leaseState = await this.readLease(leaseStream);
      const lease = this.requireActor(leaseState, {
        org: input.org,
        repo: input.repo,
        taskId: input.taskId,
        leaseId: "",
        actor: input.actor,
        token: input.token,
      });
      const capability = this.currentCapability(lease, input.token, leaseState);
      await this.assertProjectLive(leaseStream, leaseState, lease);
      const runStream = runStreamId(input.org, input.runId);
      if (lease.runId !== input.runId) throw new AgentRunError("capability/foreign-target");
      const decision = authorizeCapability({
        capability,
        token: input.token,
        lease,
        leaseState,
        operation: "run.append",
        target: { kind: "run", stream: runStream },
      });
      if (!decision.allowed) throw new AgentRunError(decision.reason);
      const run = await this.readRun(runStream);
      if (run.status !== "running") throw new AgentRunError("run/not-active");
      if (run.head !== input.expectedOffset) throw new AgentRunError("run/stale-offset");
      const offset = await this.appendFenced(runStream, input.event, input.expectedOffset);
      return { offset, run: await this.readRun(runStream) };
    });
  }

  async appendMutation(input: AgentRunMutationInput): Promise<AgentRunMutationResult> {
    if (
      !SAFE_ID.test(input.operationId) ||
      !validOffset(input.expectedTargetOffset) ||
      !safeEvent(input.mutation)
    ) {
      throw new AgentRunError("run/invalid-mutation");
    }
    const leaseStream = leaseStreamId(input.org, input.repo, input.taskId);
    return this.withLock(leaseStream, async () => {
      const leaseState = await this.readLease(leaseStream);
      const lease = this.requireActor(leaseState, {
        org: input.org,
        repo: input.repo,
        taskId: input.taskId,
        leaseId: "",
        actor: input.actor,
        token: input.token,
      });
      if (lease.runId !== input.runId) throw new AgentRunError("capability/foreign-target");
      const capability = this.currentCapability(lease, input.token, leaseState);
      await this.assertProjectLive(leaseStream, leaseState, lease);
      const decision = authorizeCapability({
        capability,
        token: input.token,
        lease,
        leaseState,
        operation:
          input.target === "branch"
            ? "branch.write"
            : input.target === "evidence"
              ? "evidence.append"
              : "verdict.append",
        target: leaseTarget(lease, input),
      });
      if (!decision.allowed) throw new AgentRunError(decision.reason);
      const runStream = runStreamId(input.org, input.runId);
      const run = await this.readRun(runStream);
      const runRecords = await this.readRaw(runStream);
      const existing = runRecordForOperation(runStream, input.operationId, runRecords);
      if (existing !== undefined) {
        return {
          receipt: {
            operationId: input.operationId,
            target: input.target,
            stream: input.stream,
            targetOffset: existing.payload.targetOffset,
          },
          run,
          runOffset: existing.offset,
        };
      }
      const intent = runIntentForOperation(runStream, input.operationId, runRecords);
      if (intent !== undefined) {
        if (
          intent.payload.target !== input.target ||
          intent.payload.stream !== input.stream ||
          intent.payload.eventType !== input.mutation.type ||
          intent.payload.mutationDigest !==
            sha256Hex(new TextEncoder().encode(canonicalJson(input.mutation))) ||
          intent.payload.expectedTargetOffset !== input.expectedTargetOffset
        ) {
          throw new AgentRunError("run/operation-collision");
        }
      } else {
        if (run.head !== input.expectedOffset) throw new AgentRunError("run/stale-offset");
        const intentEvent = runMutationIntentEvent(
          {
            operationId: input.operationId,
            target: input.target,
            stream: input.stream,
            eventType: input.mutation.type,
            mutationDigest: sha256Hex(new TextEncoder().encode(canonicalJson(input.mutation))),
            expectedTargetOffset: input.expectedTargetOffset,
          },
          this.now(),
        );
        await this.appendFenced(
          runStream,
          intentEvent,
          input.expectedOffset,
          `${input.operationId}-intent`,
        );
      }
      const targetOffset = await this.appendOrRecoverMutation(
        input.stream,
        input.mutation,
        input.expectedTargetOffset,
        input.operationId,
      );
      await this.assertProjectLive(leaseStream, await this.readLease(leaseStream), lease);
      const accepted = runMutationAcceptedEvent(
        {
          operationId: input.operationId,
          target: input.target,
          stream: input.stream,
          eventType: input.mutation.type,
          targetOffset,
        },
        this.now(),
      );
      const currentRun = await this.readRun(runStream);
      const runOffset = await this.appendFenced(runStream, accepted, currentRun.head);
      return {
        receipt: {
          operationId: input.operationId,
          target: input.target,
          stream: input.stream,
          targetOffset,
        },
        run: await this.readRun(runStream),
        runOffset,
      };
    });
  }

  async runAdapter(input: {
    readonly org: string;
    readonly repo: string;
    readonly taskId: string;
    readonly runId: string;
    readonly actor: string;
    readonly token: string;
    readonly workspace: WorkspaceManifest;
    readonly inputs: Readonly<Record<string, unknown>>;
    readonly adapter: AgentAdapter;
  }): Promise<AgentAdapterResult> {
    if (SECRET.test(canonicalJson(input.inputs))) throw new AgentRunError("run/secret-input");
    const leaseStream = leaseStreamId(input.org, input.repo, input.taskId);
    const leaseState = await this.readLease(leaseStream);
    const lease = this.requireActor(leaseState, {
      org: input.org,
      repo: input.repo,
      taskId: input.taskId,
      leaseId: "",
      actor: input.actor,
      token: input.token,
    });
    this.currentCapability(lease, input.token, leaseState);
    await this.assertProjectLive(leaseStream, leaseState, lease);
    const runStream = runStreamId(input.org, input.runId);
    const context: AgentAdapterContext = {
      role: lease.role,
      taskId: input.taskId,
      runId: input.runId,
      workspace: input.workspace,
      inputs: input.inputs,
      now: this.now,
      assertActive: async () => {
        const latest = await this.readLease(leaseStream);
        this.currentCapability(latest.active ?? lease, input.token, latest);
        if (latest.active === null || latest.active.runId !== input.runId)
          throw new AgentRunError("lease/not-active");
        await this.assertProjectLive(leaseStream, latest, latest.active);
        const currentRun = await this.readRun(runStream);
        if (currentRun.status !== "running") throw new AgentRunError("run/not-active");
      },
      append: async (event) => {
        const currentRun = await this.readRun(runStream);
        await this.appendRunEvent({
          org: input.org,
          repo: input.repo,
          taskId: input.taskId,
          runId: input.runId,
          actor: input.actor,
          token: input.token,
          expectedOffset: currentRun.head,
          event,
        });
      },
      mutate: async (request: AgentMutationRequest) => {
        const currentRun = await this.readRun(runStream);
        const targetRecords = await this.readRaw(request.stream);
        return (
          await this.appendMutation({
            org: input.org,
            repo: input.repo,
            taskId: input.taskId,
            runId: input.runId,
            actor: input.actor,
            token: input.token,
            expectedOffset: currentRun.head,
            operationId: request.operationId,
            target: request.target,
            stream: request.stream,
            expectedTargetOffset: headOf(
              targetRecords.map((record, index) => normalizeRecord(record, index)),
            ),
            mutation: request.event,
          })
        ).receipt;
      },
    };
    try {
      const result = await input.adapter.run(context);
      const currentRun = await this.readRun(runStream);
      if (result.status !== "crashed" && currentRun.status === "running") {
        await this.assertProjectLive(leaseStream, await this.readLease(leaseStream), lease);
        const liveRun = await this.readRun(runStream);
        if (liveRun.status !== "running") return result;
        await this.appendFenced(
          runStream,
          runExitedEvent(
            {
              status: result.status === "failed" ? "failed" : "completed",
              exitCode: result.status === "failed" ? 1 : 0,
            },
            this.now(),
          ),
          liveRun.head,
        );
      }
      return result;
    } catch (error) {
      if (error instanceof AgentRunError) throw error;
      if (error instanceof ScriptedCrashError) {
        // A crash is deliberately non-terminal. The next process replays the
        // run stream and the scripted operation ids make successful mutations
        // idempotent before the adapter continues.
        return { status: "crashed", mutations: 0, steps: 0 };
      }
      const currentRun = await this.readRun(runStream);
      if (currentRun.status === "running") {
        await this.appendFenced(runStream, runRevokedEvent("crashed", this.now()), currentRun.head);
      }
      return { status: "crashed", mutations: 0, steps: 0 };
    }
  }

  async inspect(input: {
    readonly org: string;
    readonly repo: string;
    readonly taskId: string;
    readonly runId: string;
  }): Promise<{ readonly lease: LeaseState; readonly run: RunState }> {
    const leaseStream = leaseStreamId(input.org, input.repo, input.taskId);
    return {
      lease: await this.readLease(leaseStream),
      run: await this.readRun(runStreamId(input.org, input.runId)),
    };
  }

  private async finishLease(
    input: AgentRunLeaseInput,
    kind: "released" | "revoked",
    reason = "lease-released",
  ): Promise<AgentRunLeaseResult> {
    return this.withLeaseLock(input, async (stream, state) => {
      const active = this.requireActor(state, input);
      this.currentCapability(active, input.token, state);
      const event =
        kind === "released"
          ? leaseReleasedEvent(active.leaseId, active.fence, this.now())
          : leaseRevokedEvent(active.leaseId, active.fence, reason, this.now());
      const offset = await this.appendFenced(
        stream,
        event,
        state.head,
        `${active.leaseId}-${kind}`,
      );
      const runStream = runStreamId(active.org, active.runId);
      const run = await this.readRun(runStream);
      if (run.status === "running") {
        await this.appendFenced(
          runStream,
          runRevokedEvent(
            kind === "released" ? "lease-released" : "capability-revoked",
            this.now(),
          ),
          run.head,
          `${active.leaseId}-run-${kind}`,
        );
      }
      return { lease: null, run: await this.readRun(runStream), offset };
    });
  }

  private async assertProjectLive(
    leaseStream: string,
    leaseState: LeaseState,
    lease: LeaseRecord,
  ): Promise<void> {
    const project = await this.currentProject(lease.org, lease.repo);
    if (project.status === "building" && project.head === lease.projectOffset) return;
    const reason: RunRevocationReason =
      project.status === "invalid_loop" ? "project-invalid" : "project-paused";
    await this.revokeActiveLease(leaseStream, leaseState, lease, reason);
    throw new AgentRunError(
      project.status === "building" ? "lease/project-offset" : "lease/project-not-building",
    );
  }

  private async revokeActiveLease(
    leaseStream: string,
    leaseState: LeaseState,
    lease: LeaseRecord,
    reason: RunRevocationReason,
  ): Promise<void> {
    if (leaseState.active?.leaseId !== lease.leaseId) return;
    await this.appendFenced(
      leaseStream,
      leaseRevokedEvent(lease.leaseId, lease.fence, reason, this.now()),
      leaseState.head,
      `${lease.leaseId}-project-${reason}`,
    );
    const runStream = runStreamId(lease.org, lease.runId);
    const run = await this.readRun(runStream);
    if (run.status === "running") {
      await this.appendFenced(
        runStream,
        runRevokedEvent(reason, this.now()),
        run.head,
        `${lease.leaseId}-run-project-${reason}`,
      );
    }
  }

  private async currentQueueProof(proof: QueueProof): Promise<QueueProof> {
    const catalog = await this.readEvents(proof.queue.stream);
    const tasks: QueueSourceStream[] = [];
    for (const head of proof.heads) {
      tasks.push({ stream: head.stream, records: await this.readEvents(head.stream) });
    }
    const check = checkQueueProof(proof, {
      catalog: { stream: proof.queue.stream, records: catalog },
      tasks,
    });
    if (!check.ok) throw new AgentRunError(check.reason);
    return check.current;
  }

  private async currentProject(org: string, repo: string) {
    const stream = projectStreamId(org, repo);
    const records = await this.readEvents(stream);
    return replayProjectLog(stream, records);
  }

  private async readLease(stream: string): Promise<LeaseState> {
    const records = await this.readRaw(stream);
    return records.length === 0
      ? leaseInitialStateForStream(stream)
      : replayLeaseLog(stream, records);
  }

  private async readRun(stream: string): Promise<RunState> {
    const records = await this.readRaw(stream);
    return records.length === 0 ? runInitialStateForStream(stream) : replayRunLog(stream, records);
  }

  private async readEvents(
    stream: string,
  ): Promise<readonly (Event & { readonly offset: Offset })[]> {
    return (await this.readRaw(stream)).map((record, index) => normalizeRecord(record, index));
  }

  private async readRaw(stream: string): Promise<readonly unknown[]> {
    try {
      return await (this.streams.readResolved?.(stream) ?? this.streams.read(stream));
    } catch (error) {
      if (isDurableNotFound(error)) return [];
      throw error;
    }
  }

  private async ensureStream(stream: string): Promise<void> {
    if (this.streams.exists !== undefined) {
      if (await this.streams.exists(stream)) return;
      try {
        await this.streams.create(stream);
      } catch (error) {
        if (!isDurableConflict(error)) throw error;
      }
      return;
    }
    try {
      await this.streams.read(stream);
    } catch (error) {
      if (!isDurableNotFound(error)) throw error;
      try {
        await this.streams.create(stream);
      } catch (createError) {
        if (!isDurableConflict(createError)) throw createError;
      }
    }
  }

  private async appendFenced(
    stream: string,
    event: Event,
    expectedHead: Offset | "-1",
    idempotencyKey?: string,
  ): Promise<Offset> {
    await this.ensureStream(stream);
    const records = await this.readEvents(stream);
    const actual = headOf(records);
    if (actual !== expectedHead) throw new AgentRunError("lease/stale-fence");
    const next = offsetForOrdinal(records.length);
    try {
      await this.streams.append(stream, event, {
        sequence: next,
        applicationOffset: next,
        ...(idempotencyKey === undefined ? {} : { idempotencyKey }),
      });
    } catch (error) {
      if (isDurableConflict(error)) throw new AgentRunError("lease/stale-fence");
      throw error;
    }
    return next;
  }

  private async appendOrRecoverMutation(
    stream: string,
    mutation: Event,
    expectedHead: Offset | "-1",
    operationId: string,
  ): Promise<Offset> {
    const records = await this.readEvents(stream);
    const actual = headOf(records);
    if (actual === expectedHead) {
      return this.appendFenced(stream, mutation, expectedHead, operationId);
    }
    const expectedIndex =
      expectedHead === OFFSET_BEFORE_FIRST
        ? -1
        : records.findIndex((record) => record.offset === expectedHead);
    const recovered = records[expectedIndex + 1];
    const recoveredEvent =
      recovered === undefined
        ? undefined
        : (() => {
            return { type: recovered.type, payload: recovered.payload, ts: recovered.ts };
          })();
    if (
      recovered === undefined ||
      recoveredEvent === undefined ||
      canonicalJson(recoveredEvent) !== canonicalJson(mutation)
    ) {
      throw new AgentRunError("lease/stale-fence");
    }
    return recovered.offset;
  }

  private identifier(prefix: string): string {
    return `${prefix}_${Buffer.from(this.random(18)).toString("base64url")}`;
  }

  private requireActor(state: LeaseState, input: AgentRunLeaseInput): LeaseRecord {
    if (state.active === null) throw new AgentRunError("lease/not-active");
    if (input.leaseId !== "" && state.active.leaseId !== input.leaseId)
      throw new AgentRunError("lease/not-found");
    if (
      state.active.org !== input.org ||
      state.active.repo !== input.repo ||
      state.active.taskId !== input.taskId
    )
      throw new AgentRunError("lease/not-found");
    if (state.active.actor !== input.actor) throw new AgentRunError("lease/actor-mismatch");
    return state.active;
  }

  private currentCapability(lease: LeaseRecord, token: string, state: LeaseState): AgentCapability {
    try {
      return capabilityForLease(lease, token);
    } catch {
      const parsed = token.match(/^cap_v1\.[A-Za-z0-9_-]+\.([0-9]+)$/);
      if (parsed !== null && Number(parsed[1]) < lease.fence)
        throw new AgentRunError("capability/stale-fence");
      throw new AgentRunError(state.active === null ? "capability/revoked" : "capability/unknown");
    }
  }

  private parseCurrentOrRecoverableToken(
    lease: LeaseRecord,
    token: string,
  ):
    | { readonly kind: "current"; readonly token: string }
    | { readonly kind: "recover"; readonly token: string }
    | { readonly kind: "invalid" } {
    const match = /^cap_v1\.([A-Za-z0-9_-]+)\.([0-9]+)$/.exec(token);
    if (match === null) return { kind: "invalid" };
    const base = match[1]!;
    const fence = Number(match[2]);
    if (capabilityBaseDigest(token) !== lease.capabilityBaseDigest) return { kind: "invalid" };
    if (fence === lease.fence && capabilityTokenDigest(token) === lease.capabilityTokenDigest)
      return { kind: "current", token };
    if (fence < lease.fence)
      return { kind: "recover", token: capabilityTokenForFence(base, lease.fence) };
    return { kind: "invalid" };
  }

  private leaseResult(lease: LeaseRecord, token: string): AgentRunLeaseResult {
    return { lease, capability: capabilityForLease(lease, token), token };
  }

  private async withLeaseLock<T>(
    input: AgentRunLeaseInput,
    fn: (stream: string, state: LeaseState) => Promise<T>,
  ): Promise<T> {
    const stream = leaseStreamId(input.org, input.repo, input.taskId);
    return this.withLock(stream, async () => fn(stream, await this.readLease(stream)));
  }

  private async withLock<T>(key: string, fn: () => Promise<T>): Promise<T> {
    const previous = this.locks.get(key) ?? Promise.resolve();
    let release!: () => void;
    const gate = new Promise<void>((resolve) => {
      release = resolve;
    });
    const tail = previous.catch(() => undefined).then(() => gate);
    this.locks.set(key, tail);
    await previous.catch(() => undefined);
    try {
      return await fn();
    } finally {
      release();
      if (this.locks.get(key) === tail) this.locks.delete(key);
    }
  }
}

function runRecordForOperation(
  stream: string,
  operationId: string,
  records: readonly unknown[],
):
  | (Extract<RunEvent, { readonly type: "run.mutation-accepted" }> & { readonly offset: Offset })
  | undefined {
  for (const [index, record] of records.entries()) {
    const normalized = normalizeRecord(record, index);
    if (normalized.type !== "run.mutation-accepted" || !isRunEvent(normalized)) continue;
    const mutation = normalized as Extract<RunEvent, { readonly type: "run.mutation-accepted" }>;
    if (mutation.payload.operationId === operationId)
      return { ...mutation, offset: offsetOf(record, index) };
  }
  void stream;
  return undefined;
}

function runIntentForOperation(
  stream: string,
  operationId: string,
  records: readonly unknown[],
): Extract<RunEvent, { readonly type: "run.mutation-intent" }> | undefined {
  for (const [index, record] of records.entries()) {
    const normalized = normalizeRecord(record, index);
    if (normalized.type !== "run.mutation-intent" || !isRunEvent(normalized)) continue;
    const intent = normalized as Extract<RunEvent, { readonly type: "run.mutation-intent" }>;
    if (intent.payload.operationId === operationId) return intent;
  }
  void stream;
  return undefined;
}
