/**
 * `QUEUE.md` rendering (E6-T04): the human-readable projection, shaped exactly like the
 * file `tools/build_queue.py` writes — same header, legend, current gate, next-up and
 * unlocks sections (each capped at ten entries), and the same per-epic task lines — so
 * the Python and TypeScript renderings of one valid graph differ only in the generator
 * line. An invalid queue renders its violations in place of the decision sections; the
 * epic listing still follows so every member stays visible.
 *
 * Links are stream-side canonical paths `epic-<n>/<id>/readme.md`: folder slugs are a
 * folder-layer name the streams do not carry.
 */
import { renderTitle } from "../folder/render.js";
import type { TaskStatus } from "../state.js";
import type { QueueProjection, QueueTask } from "./projector.js";

export const QUEUE_MARKDOWN_GENERATOR_LINE =
  "*Generated by the `queue/v1` projection over task streams — do not edit by hand.*";
/** The generator line `tools/build_queue.py` writes; the differential ignores exactly this line. */
export const BUILD_QUEUE_GENERATOR_LINE =
  "*Generated by `tools/build_queue.py` — do not edit by hand.*";
export const QUEUE_MARKDOWN_SECTION_CAP = 10;

const STATUS_ICON: Readonly<Record<TaskStatus, string>> = {
  pending: " ",
  "in-progress": "~",
  implemented: "?",
  refuted: "!",
  verified: "x",
};

const GATE_ACTION: Readonly<Record<string, string>> = {
  "in-progress": "builder working",
  implemented: "awaiting independent critic",
  refuted: "builder rework required",
};

function taskLine(task: QueueTask): string {
  const deps = task.dependsOn.join(", ") || "—";
  const cap = task.capstone ? " **[CAPSTONE]**" : "";
  const rel = `epic-${task.epic}/${task.id}/readme.md`;
  return `- [${STATUS_ICON[task.status]}] \`${task.priority.padStart(3)}\` [${task.id}](${rel}) — ${renderTitle(task.title)}${cap} *(deps: ${deps})*`;
}

function entry(task: QueueTask): string {
  return `1. **${task.id}** — ${renderTitle(task.title)}`;
}

export interface QueueSections {
  /** The active task (`in-progress`, `implemented`, `refuted`), if any. */
  readonly gate: QueueTask | undefined;
  /** Pending tasks whose dependencies are verified, in queue order, at most ten. */
  readonly nextUp: readonly QueueTask[];
  /** Pending tasks that need only the gate to verify, not already in `nextUp`, at most ten. */
  readonly unlocks: readonly QueueTask[];
}

/** The three decision sections of `QUEUE.md`, computed exactly as `build_queue.py` does. */
export function queueSections(projection: QueueProjection): QueueSections {
  const decision = projection.decision;
  const gate =
    decision.kind === "invalid" || decision.inFlight === null
      ? undefined
      : projection.tasks.find((task) => task.id === decision.inFlight);
  const nextUp = projection.tasks
    .filter((task) => task.status === "pending" && task.blocked.length === 0)
    .slice(0, QUEUE_MARKDOWN_SECTION_CAP);
  if (gate === undefined) return { gate, nextUp, unlocks: [] };
  const nextIds = new Set(nextUp.map((task) => task.id));
  const unlocks = projection.tasks
    .filter(
      (task) =>
        task.status === "pending" &&
        !nextIds.has(task.id) &&
        task.blocked.every(
          (reason) => reason.reason === "dep/unverified" && reason.ref === gate.id,
        ),
    )
    .slice(0, QUEUE_MARKDOWN_SECTION_CAP);
  return { gate, nextUp, unlocks };
}

export interface NormalizedQueueDecision {
  readonly gate: string | null;
  readonly nextUp: readonly string[];
  /** What a builder is told to do next: the gate, else the first next-up task, else nothing. */
  readonly selected: string | null;
  readonly tuples: readonly (readonly [string, TaskStatus, string, readonly string[], boolean])[];
  readonly unlocks: readonly string[];
}

/**
 * The fetch-order-free, generator-free view both implementations must agree on; the
 * Python side (`tools/verify/queue_differential.py`) derives the same object from the
 * `QUEUE.md` that `build_queue.py` writes.
 */
export function normalizeQueueDecision(projection: QueueProjection): NormalizedQueueDecision {
  const { gate, nextUp, unlocks } = queueSections(projection);
  const gateId = gate?.id ?? null;
  return {
    gate: gateId,
    nextUp: nextUp.map((task) => task.id),
    selected: gateId ?? nextUp[0]?.id ?? null,
    tuples: projection.tasks.map(
      (task) => [task.id, task.status, task.priority, task.dependsOn, task.capstone] as const,
    ),
    unlocks: unlocks.map((task) => task.id),
  };
}

export function renderQueueMarkdown(
  projection: QueueProjection,
  generatorLine = QUEUE_MARKDOWN_GENERATOR_LINE,
): string {
  const lines: string[] = [
    "# electric-forest Priority Queue",
    "",
    generatorLine,
    "",
    `**${projection.verified} / ${projection.tasks.length} tasks verified.**`,
    "",
    "Legend: `[ ]` pending · `[~]` in-progress · `[?]` implemented (awaiting adversarial verification) · `[!]` refuted · `[x]` verified · `[-]` cancelled",
    "",
  ];
  const decision = projection.decision;
  if (decision.kind === "invalid") {
    lines.push("## Invalid queue", "");
    lines.push("No task may be selected: the queue proof is invalid.", "");
    for (const violation of decision.violations) {
      lines.push(`- \`${violation.reason}\`: ${violation.refs.join(", ")}`);
    }
    lines.push("");
  } else {
    const { gate, nextUp, unlocks } = queueSections(projection);
    lines.push("## Current gate", "");
    if (gate === undefined) {
      lines.push("No task is currently in progress, awaiting verification, or refuted.");
    } else {
      lines.push(`1. **${gate.id}** — ${renderTitle(gate.title)} *(${GATE_ACTION[gate.status]})*`);
    }
    lines.push("", "## Next up (deps satisfied, in priority order)", "");
    for (const task of nextUp) lines.push(entry(task));
    if (nextUp.length === 0) {
      lines.push(
        gate === undefined
          ? "No pending task currently has all dependencies verified."
          : `No new task may start until **${gate.id}** clears the current gate.`,
      );
    }
    if (gate !== undefined) {
      lines.push("", `## Unlocks when ${gate.id} verifies`, "");
      if (unlocks.length > 0) for (const task of unlocks) lines.push(entry(task));
      else lines.push("No task unlocks directly; an epic capstone or another dependency remains.");
    }
    lines.push("");
  }
  let currentEpic: number | undefined;
  for (const task of projection.tasks) {
    if (task.epic !== currentEpic) {
      currentEpic = task.epic;
      lines.push("", `## Epic ${currentEpic} — \`epic-${currentEpic}\``, "");
    }
    lines.push(taskLine(task));
  }
  return `${lines.join("\n")}\n`;
}
