#!/usr/bin/env python3
"""Regenerate .eforest/tasks/QUEUE.md from task-readme frontmatter.

Usage: python3 tools/build_queue.py
Stdlib only. Parses the flat-YAML frontmatter described in .eforest/tasks/README.md.
A task is a FOLDER (E{n}-T{nn}-{slug}/) whose spec lives in readme.md.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TASKS = ROOT / ".eforest" / "tasks"
QUEUE = TASKS / "QUEUE.md"

STATUS_ICON = {
    "pending": " ",
    "in-progress": "~",
    "in_progress": "~",  # both spellings appear in the wild
    "implemented": "?",
    "refuted": "!",
    "verified": "x",
    "cancelled": "-",
}


def parse_frontmatter(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    fm: dict = {"_path": path}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.split("#")[0].strip()
        if key == "depends_on":
            fm[key] = [d.strip() for d in val.strip("[]").split(",") if d.strip()]
        elif key == "priority":
            fm[key] = float(val) if "." in val else int(val)
        elif key == "epic":
            # Fractional epics are allowed; keep whole numbers as int so headers
            # print "Epic 3", not "Epic 3.0".
            fm[key] = int(val) if val.isdigit() else float(val)
        elif key == "capstone":
            fm[key] = val.lower() == "true"
        else:
            fm[key] = val
    return fm


def main() -> int:
    tasks = []
    for path in sorted(TASKS.glob("epic-*/E*-T*/readme.md")):
        fm = parse_frontmatter(path)
        if fm is None or "id" not in fm:
            print(f"warning: skipping {path} (bad frontmatter)", file=sys.stderr)
            continue
        # The folder name must agree with the frontmatter id — a mismatch means the
        # board and the tree disagree about what this task even is.
        folder_id = re.match(r"(E[0-9.]+-T[0-9]+[ab]?)", path.parent.name)
        if not folder_id or folder_id.group(1) != fm["id"]:
            print(
                f"warning: {path.parent.name}/readme.md frontmatter id {fm['id']!r}"
                " does not match its folder name",
                file=sys.stderr,
            )
        tasks.append(fm)

    if not tasks:
        print("no tasks found", file=sys.stderr)
        return 1

    tasks.sort(key=lambda t: t.get("priority", 9999))

    ids = {t["id"] for t in tasks}
    dupes = len(tasks) - len(ids)
    if dupes:
        print(f"warning: {dupes} duplicate task id(s)", file=sys.stderr)

    verified = {t["id"] for t in tasks if t.get("status") == "verified"}
    capstone_verified = {
        f"E{t['epic']}" for t in tasks if t.get("capstone") and t.get("status") == "verified"
    }
    done_refs = verified | capstone_verified

    def eligible(t: dict) -> bool:
        if t.get("status") not in ("pending", "refuted"):
            return False
        return all(dep in done_refs for dep in t.get("depends_on", []))

    next_up = [t for t in tasks if eligible(t)][:10]
    n_verified = len(verified)

    lines = [
        "# electric-forest Priority Queue",
        "",
        "*Generated by `tools/build_queue.py` — do not edit by hand.*",
        "",
        f"**{n_verified} / {len(tasks)} tasks verified.**",
        "",
        "Legend: `[ ]` pending · `[~]` in-progress · `[?]` implemented (awaiting"
        " adversarial verification) · `[!]` refuted · `[x]` verified · `[-]` cancelled",
        "",
        "## Next up (deps satisfied, in priority order)",
        "",
    ]
    for t in next_up:
        lines.append(f"1. **{t['id']}** — {t.get('title', '?')}")
    lines.append("")

    current_epic = None
    for t in tasks:
        if t.get("epic") != current_epic:
            current_epic = t.get("epic")
            epic_dir = t["_path"].parent.parent.name
            lines += ["", f"## Epic {current_epic} — `{epic_dir}`", ""]
        status = t.get("status", "pending")
        if status not in STATUS_ICON:
            # An unknown status must not silently render as pending — the board would lie.
            print(f"warning: {t['id']} has unknown status {status!r}", file=sys.stderr)
        icon = STATUS_ICON.get(status, " ")
        rel = t["_path"].relative_to(TASKS).as_posix()
        deps = ", ".join(t.get("depends_on", [])) or "—"
        cap = " **[CAPSTONE]**" if t.get("capstone") else ""
        lines.append(
            f"- [{icon}] `{t.get('priority', '?'):>3}` [{t['id']}]({rel})"
            f" — {t.get('title', '?')}{cap} *(deps: {deps})*"
        )

    QUEUE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {QUEUE.relative_to(ROOT)}: {len(tasks)} tasks, {n_verified} verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
